/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ./public/model/torii/tori.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Torii(props) {
  const { nodes, materials } = useGLTF('./model/torii/tori.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['Node-Mesh'].geometry} material={materials.mat23} />
      <mesh geometry={nodes['Node-Mesh_1'].geometry} material={materials.mat14} />
    </group>
  )
}

useGLTF.preload('./model/torii/tori.glb')
